repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/biomejs/pre-commit
    rev: v0.6.1
    hooks:
      - id: biome-check

  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint run
        entry: golangci-lint run --new-from-rev HEAD --fix
        types: [ go ]
        language: golang
      - id: golangci-lint-fmt
        name: golangci-lint-fmt
        entry: golangci-lint fmt
        types: [ go ]
        language: golang
