packages:
  - apps/*
  - packages/*

catalog:
  lucide-react: ^0.475.0
  next-themes: ^0.4.6
  typescript: 5.9.3

catalogs:
  react19:
    '@types/node': ^24.7.0
    '@types/react': ^19.2.0
    '@types/react-dom': ^19.2.0
    next: ^15.4.5
    react: ^19.1.1
    react-dom: ^19.1.1

onlyBuiltDependencies:
  - sharp
