packages:
  - apps/*
  - packages/*
  - infrastructure

catalog:
  '@tailwindcss/postcss': ^4.1.17
  '@testing-library/dom': 10.4.1
  '@testing-library/jest-dom': 6.9.1
  '@testing-library/react': ^16.3.0
  '@types/node': ^24.10.1
  '@types/react': ^19.2.4
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.1
  '@vitest/coverage-istanbul': 4.0.8
  jsdom: ^27.2.0
  lucide-react: 0.553.0
  next: ^16.0.3
  react: 19.2.0
  react-dom: 19.2.0
  typescript: ^5.9.3
  vite-tsconfig-paths: ^5.1.4
  vitest: 4.0.8
