// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package utils

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPasswordUtils creates a new instance of MockPasswordUtils. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordUtils(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordUtils {
	mock := &MockPasswordUtils{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordUtils is an autogenerated mock type for the PasswordUtils type
type MockPasswordUtils struct {
	mock.Mock
}

type MockPasswordUtils_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordUtils) EXPECT() *MockPasswordUtils_Expecter {
	return &MockPasswordUtils_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function for the type MockPasswordUtils
func (_mock *MockPasswordUtils) Hash(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordUtils_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockPasswordUtils_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - password string
func (_e *MockPasswordUtils_Expecter) Hash(password interface{}) *MockPasswordUtils_Hash_Call {
	return &MockPasswordUtils_Hash_Call{Call: _e.mock.On("Hash", password)}
}

func (_c *MockPasswordUtils_Hash_Call) Run(run func(password string)) *MockPasswordUtils_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPasswordUtils_Hash_Call) Return(s string, err error) *MockPasswordUtils_Hash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPasswordUtils_Hash_Call) RunAndReturn(run func(password string) (string, error)) *MockPasswordUtils_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockPasswordUtils
func (_mock *MockPasswordUtils) Verify(hash string, raw string) error {
	ret := _mock.Called(hash, raw)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(hash, raw)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPasswordUtils_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockPasswordUtils_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - hash string
//   - raw string
func (_e *MockPasswordUtils_Expecter) Verify(hash interface{}, raw interface{}) *MockPasswordUtils_Verify_Call {
	return &MockPasswordUtils_Verify_Call{Call: _e.mock.On("Verify", hash, raw)}
}

func (_c *MockPasswordUtils_Verify_Call) Run(run func(hash string, raw string)) *MockPasswordUtils_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPasswordUtils_Verify_Call) Return(err error) *MockPasswordUtils_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPasswordUtils_Verify_Call) RunAndReturn(run func(hash string, raw string) error) *MockPasswordUtils_Verify_Call {
	_c.Call.Return(run)
	return _c
}
