// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"context"

	"github.com/0xlebogang/envy/backend/internal/domain/models"
	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, u *models.User) (*models.User, error) {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) (*models.User, error)); ok {
		return returnFunc(ctx, u)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) *models.User); ok {
		r0 = returnFunc(ctx, u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.User) error); ok {
		r1 = returnFunc(ctx, u)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - u *models.User
func (_e *MockRepository_Expecter) Create(ctx interface{}, u interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, u)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, u *models.User)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.User
		if args[1] != nil {
			arg1 = args[1].(*models.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(user *models.User, err error) *MockRepository_Create_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, u *models.User) (*models.User, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRepository
func (_mock *MockRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(err error) *MockRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *MockRepository_GetByEmail_Call {
	return &MockRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByEmail_Call) Return(user *models.User, err error) *MockRepository_GetByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*models.User, error)) *MockRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByID(ctx context.Context, id string) (*models.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(user *models.User, err error) *MockRepository_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.User, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRepository
func (_mock *MockRepository) List(ctx context.Context) (*[]models.User, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *[]models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*[]models.User, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *[]models.User); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) List(ctx interface{}) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(users *[]models.User, err error) *MockRepository_List_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(ctx context.Context) (*[]models.User, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRepository
func (_mock *MockRepository) Update(ctx context.Context, id string, u *models.User) (*models.User, error) {
	ret := _mock.Called(ctx, id, u)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *models.User) (*models.User, error)); ok {
		return returnFunc(ctx, id, u)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *models.User) *models.User); ok {
		r0 = returnFunc(ctx, id, u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *models.User) error); ok {
		r1 = returnFunc(ctx, id, u)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - u *models.User
func (_e *MockRepository_Expecter) Update(ctx interface{}, id interface{}, u interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, u)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, id string, u *models.User)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *models.User
		if args[2] != nil {
			arg2 = args[2].(*models.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(user *models.User, err error) *MockRepository_Update_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(ctx context.Context, id string, u *models.User) (*models.User, error)) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// FindByEmail provides a mock function for the type MockService
func (_mock *MockService) FindByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockService_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockService_Expecter) FindByEmail(ctx interface{}, email interface{}) *MockService_FindByEmail_Call {
	return &MockService_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockService_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockService_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_FindByEmail_Call) Return(user *models.User, err error) *MockService_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockService_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*models.User, error)) *MockService_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockService
func (_mock *MockService) FindByID(ctx context.Context, id string) (*models.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockService_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) FindByID(ctx interface{}, id interface{}) *MockService_FindByID_Call {
	return &MockService_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockService_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockService_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_FindByID_Call) Return(user *models.User, err error) *MockService_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockService_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.User, error)) *MockService_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function for the type MockService
func (_mock *MockService) GetAllUsers(ctx context.Context) (*[]models.User, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 *[]models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*[]models.User, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *[]models.User); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type MockService_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetAllUsers(ctx interface{}) *MockService_GetAllUsers_Call {
	return &MockService_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers", ctx)}
}

func (_c *MockService_GetAllUsers_Call) Run(run func(ctx context.Context)) *MockService_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetAllUsers_Call) Return(users *[]models.User, err error) *MockService_GetAllUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockService_GetAllUsers_Call) RunAndReturn(run func(ctx context.Context) (*[]models.User, error)) *MockService_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockService
func (_mock *MockService) Register(ctx context.Context, u *models.User) (*models.User, error) {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) (*models.User, error)); ok {
		return returnFunc(ctx, u)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) *models.User); ok {
		r0 = returnFunc(ctx, u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.User) error); ok {
		r1 = returnFunc(ctx, u)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - u *models.User
func (_e *MockService_Expecter) Register(ctx interface{}, u interface{}) *MockService_Register_Call {
	return &MockService_Register_Call{Call: _e.mock.On("Register", ctx, u)}
}

func (_c *MockService_Register_Call) Run(run func(ctx context.Context, u *models.User)) *MockService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.User
		if args[1] != nil {
			arg1 = args[1].(*models.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Register_Call) Return(user *models.User, err error) *MockService_Register_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockService_Register_Call) RunAndReturn(run func(ctx context.Context, u *models.User) (*models.User, error)) *MockService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAccount provides a mock function for the type MockService
func (_mock *MockService) RemoveAccount(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RemoveAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAccount'
type MockService_RemoveAccount_Call struct {
	*mock.Call
}

// RemoveAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) RemoveAccount(ctx interface{}, id interface{}) *MockService_RemoveAccount_Call {
	return &MockService_RemoveAccount_Call{Call: _e.mock.On("RemoveAccount", ctx, id)}
}

func (_c *MockService_RemoveAccount_Call) Run(run func(ctx context.Context, id string)) *MockService_RemoveAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_RemoveAccount_Call) Return(err error) *MockService_RemoveAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RemoveAccount_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockService_RemoveAccount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserProfile provides a mock function for the type MockService
func (_mock *MockService) UpdateUserProfile(ctx context.Context, id string, u *models.User) (*models.User, error) {
	ret := _mock.Called(ctx, id, u)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserProfile")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *models.User) (*models.User, error)); ok {
		return returnFunc(ctx, id, u)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *models.User) *models.User); ok {
		r0 = returnFunc(ctx, id, u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *models.User) error); ok {
		r1 = returnFunc(ctx, id, u)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UpdateUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserProfile'
type MockService_UpdateUserProfile_Call struct {
	*mock.Call
}

// UpdateUserProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - u *models.User
func (_e *MockService_Expecter) UpdateUserProfile(ctx interface{}, id interface{}, u interface{}) *MockService_UpdateUserProfile_Call {
	return &MockService_UpdateUserProfile_Call{Call: _e.mock.On("UpdateUserProfile", ctx, id, u)}
}

func (_c *MockService_UpdateUserProfile_Call) Run(run func(ctx context.Context, id string, u *models.User)) *MockService_UpdateUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *models.User
		if args[2] != nil {
			arg2 = args[2].(*models.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_UpdateUserProfile_Call) Return(user *models.User, err error) *MockService_UpdateUserProfile_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockService_UpdateUserProfile_Call) RunAndReturn(run func(ctx context.Context, id string, u *models.User) (*models.User, error)) *MockService_UpdateUserProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockHandler
func (_mock *MockHandler) CreateUser() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockHandler_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockHandler_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
func (_e *MockHandler_Expecter) CreateUser() *MockHandler_CreateUser_Call {
	return &MockHandler_CreateUser_Call{Call: _e.mock.On("CreateUser")}
}

func (_c *MockHandler_CreateUser_Call) Run(run func()) *MockHandler_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_CreateUser_Call) Return(handlerFunc gin.HandlerFunc) *MockHandler_CreateUser_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockHandler_CreateUser_Call) RunAndReturn(run func() gin.HandlerFunc) *MockHandler_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockHandler
func (_mock *MockHandler) DeleteUser() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockHandler_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockHandler_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
func (_e *MockHandler_Expecter) DeleteUser() *MockHandler_DeleteUser_Call {
	return &MockHandler_DeleteUser_Call{Call: _e.mock.On("DeleteUser")}
}

func (_c *MockHandler_DeleteUser_Call) Run(run func()) *MockHandler_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_DeleteUser_Call) Return(handlerFunc gin.HandlerFunc) *MockHandler_DeleteUser_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockHandler_DeleteUser_Call) RunAndReturn(run func() gin.HandlerFunc) *MockHandler_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function for the type MockHandler
func (_mock *MockHandler) GetAllUsers() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockHandler_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type MockHandler_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
func (_e *MockHandler_Expecter) GetAllUsers() *MockHandler_GetAllUsers_Call {
	return &MockHandler_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers")}
}

func (_c *MockHandler_GetAllUsers_Call) Run(run func()) *MockHandler_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_GetAllUsers_Call) Return(handlerFunc gin.HandlerFunc) *MockHandler_GetAllUsers_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockHandler_GetAllUsers_Call) RunAndReturn(run func() gin.HandlerFunc) *MockHandler_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockHandler
func (_mock *MockHandler) GetUserByEmail() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockHandler_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockHandler_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
func (_e *MockHandler_Expecter) GetUserByEmail() *MockHandler_GetUserByEmail_Call {
	return &MockHandler_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail")}
}

func (_c *MockHandler_GetUserByEmail_Call) Run(run func()) *MockHandler_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_GetUserByEmail_Call) Return(handlerFunc gin.HandlerFunc) *MockHandler_GetUserByEmail_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockHandler_GetUserByEmail_Call) RunAndReturn(run func() gin.HandlerFunc) *MockHandler_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockHandler
func (_mock *MockHandler) GetUserByID() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockHandler_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockHandler_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
func (_e *MockHandler_Expecter) GetUserByID() *MockHandler_GetUserByID_Call {
	return &MockHandler_GetUserByID_Call{Call: _e.mock.On("GetUserByID")}
}

func (_c *MockHandler_GetUserByID_Call) Run(run func()) *MockHandler_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_GetUserByID_Call) Return(handlerFunc gin.HandlerFunc) *MockHandler_GetUserByID_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockHandler_GetUserByID_Call) RunAndReturn(run func() gin.HandlerFunc) *MockHandler_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockHandler
func (_mock *MockHandler) UpdateUser() gin.HandlerFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 gin.HandlerFunc
	if returnFunc, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}
	return r0
}

// MockHandler_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockHandler_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
func (_e *MockHandler_Expecter) UpdateUser() *MockHandler_UpdateUser_Call {
	return &MockHandler_UpdateUser_Call{Call: _e.mock.On("UpdateUser")}
}

func (_c *MockHandler_UpdateUser_Call) Run(run func()) *MockHandler_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_UpdateUser_Call) Return(handlerFunc gin.HandlerFunc) *MockHandler_UpdateUser_Call {
	_c.Call.Return(handlerFunc)
	return _c
}

func (_c *MockHandler_UpdateUser_Call) RunAndReturn(run func() gin.HandlerFunc) *MockHandler_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
