name: 'Setup Development Tools'
description: 'Sets up Go, Golangci-Lint, Node.js, PNPM, and Turbo for the workflow'

inputs:
  go-version:
    description: 'Version of Go to setup'
    required: true
  golangci-lint-version:
    description: 'Version of Golangci-Lint to setup (set to "none" to skip)'
    required: true
  node-version:
    description: 'Version of Node.js to setup'
    required: true
  pnpm-version:
    description: 'Version of PNPM to setup'
    required: true
  turbo-version:
    description: 'Version of Turbo to setup'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}

    - name: Setup Golangci-Lint
      if: ${{ inputs.golangci-lint-version != 'none' || inputs.golangci-lint-version != '' }}
      uses: golangci/golangci-lint-action@v9
      with:
        version: ${{ inputs.golangci-lint-version }}

    - name: Setup PNPM
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install Project Dependencies
      shell: bash
      run: |
        pnpm add -g turbo@${{ inputs.turbo-version }}
        pnpm install --frozen-lockfile
