name: Setup Tools
description: An action to set up all necessary tools for the project.

inputs:
  turbo-version:
    description: Version of Turborepo to install globally
    required: false
    default: 'latest'

runs:
  using: composite
  steps:
    - name: Install Mise
      shell: bash
      run: |
        curl -fsSL https://mise.run | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install tools via Mise
      shell: bash
      run: |
        mise install

    - name: Install global dependencies
      shell: bash
      run: |
        npm install -g turbo@{{ inputs.turbo-version }}
        pnpm install --frozen-lockfile
